fixed a bug related to Task Ownership
health-care-app/trip-tap pull request #4
Opened 2020-08-27 12:32 UTC by abdallahdak7

2020-09-01 08:54 UTC, Khousheish requested changes

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +
remove space

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +
remove

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +
remove

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +
remove

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.service.ts
> +
remove

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.service.ts
> +
remove

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +        @GetUser() user: User,
all files are indented with 4 spaces please refactor to use 2

2020-09-01 08:54 UTC, Khousheish commented on src/auth/admin.controller.ts
> +        @GetUser() user: User,
check all files

2020-09-01 19:24 UTC, Khousheish requested changes

2020-09-01 19:24 UTC, Khousheish commented on src/auth/get-user.decorator.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/auth/user.repository.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/auth/user.repository.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/auth/user.repository.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/auth/user.repository.ts
> +      // tslint:disable-next-line: no-console
remove these 2 lines

2020-09-01 19:24 UTC, Khousheish commented on src/auth/user.repository.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/customer.trips.controller.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/dto/create-trip.dto.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trip.entity.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trip.entity.ts
> +  // tslint:disable-next-line: typedef
cant you add the type def to these? they seem simple

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trip.repository.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trip.repository.ts
> +    if (user.userType === UserType.tripOrganizer) {
space

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.spec.ts
> +// tslint:disable-next-line: typedef
type void add and remove disable

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.spec.ts
> +  // tslint:disable-next-line: typedef
check rest of files

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.controller.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.service.spec.ts
> +  // tslint:disable-next-line: typedef
fix in all the file

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.service.ts
> +
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.service.ts
remove

2020-09-01 19:24 UTC, Khousheish commented on src/trips/trips.service.ts
> +
remove

2020-09-04 11:45 UTC, IVmostafa approved these changes

2020-09-05 18:16 UTC, Khousheish approved these changes

2020-09-05 18:52 UTC, merged